### ISSUE TITLE
STLParser - Normalen aus stl lesen

### ISSUE THREAD

**Issue by Smirrorgame** [Smirrorgame/StyroCutRobot#11]
Momentan wird die Normale eines Dreiecks noch berechnet.
Ziel ist es, dass der Parser die Normale aus der Datei ausliest, da diese Information dort schon vorhanden ist und eine Berechnung  zu falschen Vorzeichen führen kann.

**Comment by DezzardHD** [comment]
Wir können annehmen, dass die Eckpunkte der Dreiecke aus der STL Datei geordnet sind, sodass die Orientierung  der Reihenfolge der Eckpunkte negativ ist. Somit kann die Berechnung der Normalen problemlos bei der Initialisierung der Dreiecke geschehen.
Damit wird das Auslesen der Normalen überflüssig.

**Comment by Smirrorgame** [comment]
Also wenn du die Berechnung gerne implementieren/auf Richtigkeit prüfen möchtest kannst du das gerne machen. Ich dachte nur, dass es komfortabler (und weniger Rechenaufwand) ist die Normalen auszulesen, da die Info sowieso schon vorhanden ist.

**Comment by DezzardHD** [comment]
Theoretisch wäre es nicht so rechenaufwändig, hattest du die Normalenberechnung bereits implementiert gehabt, wobei wir damals noch nicht wussten, dass die Normalen nach außen zeigen müssen, bzw. wussten wir nicht, wie man das berechnen kann.
Jetzt wissen wir ja, dass es dafür einer negativen Orientierung bedarf.
Habe die Berechnung in der Klasse Triangle angepasst, sollte also so funktionieren.
