### ISSUE TITLE
Array mit gemessenen Marker-Orientierungen wird nicht gecleared

### ISSUE THREAD

**Issue by Smirrorgame** [Smirrorgame/StyroCutRobot#4]
In QR24.java wird das `measuredPosesOfMarker` Array niemals gecleared, das heißt bei mehreren Kalibrierungen bleiben die alten Posen noch erhalten.

In der `createRobotPoseHomMatrices()` in QR24.java wird am Anfang das `poseMatrices` Array gecleared, hier kann man auch das `measuredPosesOfMarker` clearen

**Comment by DezzardHD** [comment]
Stimme zu.
