### ISSUE TITLE
Die letzen zwei Markerwerte beim Abfragen der Werte werden nicht in die Matrix gespeichert

### ISSUE THREAD

**Issue by Smirrorgame** [Smirrorgame/StyroCutRobot#5]
Beim Parsen des Strings mit der Markermatrix in Constants.java in `convertPoseDataToDoubleArray(String data, int index)` werden die letzten zwei Werte nicht in die Matrix gespeichert.

Das kann behoben werden, indem man die for-Schleife statt von `dataDoubleArray.length` bis `dataDoubleArray.length+index` laufen lässt, also
```java
for(int counter = index; counter < dataDoubleArray.length; counter++) {
    dataDoubleArray[counter-index] = Double.parseDouble(dataStringArray[counter]);
}
```
ersetzen mit

```java
for(int counter = index; counter < dataDoubleArray.length+index; counter++) {
    dataDoubleArray[counter-index] = Double.parseDouble(dataStringArray[counter]);
}
```

**Comment by DezzardHD** [comment]
Stimme zu. ^^
