### ISSUE TITLE
Orthonormalisierung des Rotationsteils der X-/Y-Matrizen

### ISSUE THREAD

**Issue by Smirrorgame** [Smirrorgame/StyroCutRobot#8]
Momentan ist im Code in calibrate() noch die Orthonormalisierung mittels SingularValueDecomposition (SVD) implementiert.

Hat sich herausgestellt, dass das nicht ganz so richtig ist. Stattdessen würde ich eine einfache Normierung vorschlagen, also jeweils die Vektoren des Rotationsteils der Matrizen durch ihre Norm teilen.

```java
// normalize rotational part
RealVector nx = X.getColumnVector(0);
RealVector ox = X.getColumnVector(1);
RealVector px = X.getColumnVector(2);
		
nx.mapDivideToSelf(nx.getNorm());
ox.mapDivideToSelf(ox.getNorm());
px.mapDivideToSelf(px.getNorm());
		
X.setColumnVector(0, nx);
X.setColumnVector(1, ox);
X.setColumnVector(2, px);
		
RealVector ny = Y.getColumnVector(0);
RealVector oy = Y.getColumnVector(1);
RealVector py = Y.getColumnVector(2);
		
ny.mapDivideToSelf(ny.getNorm());
oy.mapDivideToSelf(oy.getNorm());
py.mapDivideToSelf(py.getNorm());
		
Y.setColumnVector(0, ny);
Y.setColumnVector(1, oy);
Y.setColumnVector(2, py);
```

**Comment by DezzardHD** [comment]
Also möchtest du nur sicherstellen, dass die Achsen des berechneten Koordinatensystems alle der Länge 1 entsprechen?

Wo genau lag der Fehler bei der Orthonormalisierung?
Die dürfte theoretisch dafür sorgen, dass das Rechtskoordinatensystem auch wirklich linear unabhängige Vektoren beinhaltet.
Ob die Vektoren bzgl. ihrer Länge normiert werden, weiß ich allerdings nicht.

**Comment by Smirrorgame** [comment]
Bei einer Orthogonalisierung wird aus den gegebenen Vektoren eine Orthogonalbasis berechnet, bei der Orthonormalisierung passiert das gleiche, nur entspricht die Länge der Basis immer genau 1.

Das Problem ist, dass die Werte aus der SVD schlicht falsch sind. Wenn mir der QR24 eine Rotationsmatrix R = 
![alt text](https://www.zahlen-kern.de/editor/equations/16zb7.png "Rotationsmatrix")
ausgibt und ich SVD auf die Matrix anwende, dann kommt nicht sowas schönes wie vorher raus, sondern sowas in etwa:
![alt text](https://www.zahlen-kern.de/editor/equations/16zbf.png "Rotationsmatrix")
(Sind jetzt nicht genau die Werte, die bei dem Input rauskommen, aber in genau dem Feld bewegen sich die Werte)

Dadurch würden wir uns die Matrizen einfach komplett kaputt machen, da ist es doch (zumindest erstmal) einfacher und besser, wenn wir die berechneten Matrizen nehmen und die Vektoren zumindest auf die Länge 1 normieren. Die Komponentenanteile der Vektoren bleiben dadurch ja trotzdem im Verhältnis
